name: release-branch

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  branch-out:
    name: Create a github branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the branch version
        id: get_branch
        run: |
          BRANCH=${GITHUB_REF/refs\/tags\//}
          if ${{github.event_name == 'workflow_dispatch'}}; then
            BRANCH=$(git describe --abbrev=0 --tags)
          fi
          echo "BRANCH=$(echo ${BRANCH} | cut -d '.' -f1-2 | tr -d 'v')" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: Bump patch version
        run: make patch

      - name: Create new branch and commit changes to the minor branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: 'Update patch version'
          new_branch: ${{ steps.get_branch.outputs.BRANCH }}
          author_name: elasticcloudclients
          author_email: elasticcloudclients@elastic.co

  bump-minor-version:
    name: Bump main version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_EXTRA }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: Bump main version
        run: make minor; git diff

      - name: Commit changes to main
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: 'Update minor version'
          branch: master
          author_name: elasticcloudclients
          author_email: elasticcloudclients@elastic.co
