name: goreleaser

on:
  push:
    tags:
      - '*.*.*'

jobs:
  goreleaser:
    name: Release a new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install hub
        uses: geertvdc/setup-hub@master

      - name: Update AWS cli
        uses: chrislennon/action-aws-cli@v1.1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the builtvar
        id: get_built
        run: echo ::set-output name=BUILT::$(date -u +%a_%d_%b_%H:%M:%S_%Y)

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_EXTRA }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          BUILT: ${{ steps.get_built.outputs.BUILT }}
          OWNER: elastic
          REPO: ecctl
        with:
          version: latest
          args: release --rm-dist

      - name: Run release post actions
        run: ./scripts/goreleaser-post-actions.sh $VERSION
        env:
          # elasticcloudmachine GitHub token.
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GH_TOKEN }}
          GITHUB_USER: marclop
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
